version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1 # Elasticsearch and Kibana versions 7.12.1 (you can change these versions to match your requirements).
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limited JVM heap size for Elasticsearch to 512m for both minimum and maximum to prevent memory issues on smaller servers. Adjust this value based on your server's resources.
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch_docker_volumes/data:/usr/share/elasticsearch/data # Persistent mounted for Elasticsearch data to ensure data persistence. Change /usr/share/elasticsearch_docker_volumes/data this to your specific requirements.
    ports:
      - "9200:9200" # Customize Elasticsearch port here
    networks:
      - elastic # A custom network elastic for communication between services.

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601" # Customize Kibana port here
    networks:
      - elastic

volumes:
  esdata1:
    driver: local

networks:
  elastic:
    driver: bridge
